import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onInverseSurface,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.green900,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20.h),
          ),
          shadowColor: colorScheme.primary,
          elevation: 4,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        headlineSmall: TextStyle(
          color: colorScheme.background,
          fontSize: 25.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: colorScheme.background,
          fontSize: 20.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XAB000000),
    secondary: Color(0XAB000000),
    secondaryContainer: Color(0X3F000000),
    tertiary: Color(0XAB000000),
    tertiaryContainer: Color(0X3F000000),

    // Background colors
    background: Color(0XAB000000),

    // Surface colors
    surface: Color(0XAB000000),
    surfaceTint: Color(0XFF0A5C03),
    surfaceVariant: Color(0X3F000000),

    // Error colors
    error: Color(0XFF0A5C03),
    errorContainer: Color(0XABEEEEEE),
    onError: Color(0XFFFFFFFF),
    onErrorContainer: Color(0XFF0A5C03),

    // On colors(text colors)
    onBackground: Color(0XFF0A5C03),
    onInverseSurface: Color(0XFFFFFFFF),
    onPrimary: Color(0XFF0A5C03),
    onPrimaryContainer: Color(0XFF0A5C03),
    onSecondary: Color(0XFF0A5C03),
    onSecondaryContainer: Color(0XFF0A5C03),
    onTertiary: Color(0XFF0A5C03),
    onTertiaryContainer: Color(0XFF0A5C03),

    // Other colors
    outline: Color(0XFF0A5C03),
    outlineVariant: Color(0XAB000000),
    scrim: Color(0XAB000000),
    shadow: Color(0XFF0A5C03),

    // Inverse colors
    inversePrimary: Color(0XAB000000),
    inverseSurface: Color(0XFF0A5C03),

    // Pending colors
    onSurface: Color(0XFF0A5C03),
    onSurfaceVariant: Color(0XFF0A5C03),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // GrayAb
  Color get gray200Ab => Color(0XABEEEEEE);

  // Gray
  Color get gray800 => Color(0XFF434343);

  // Green
  Color get green900 => Color(0XFF245B1F);
  Color get green90001 => Color(0XFF0D5D06);

  // White
  Color get whiteA700 => Color(0XFFFFFCFC);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
